### ISSUE TITLE
Feature request: ignore copy for sensitive applications ie. password managers

### ISSUE THREAD

**Issue by bunk3m** [snark/jumpcut#10]
Hi.
I've been using Jumpcut for some time and love it.  Thanks for putting in the time to make a very useful application for the Mac.  I've noticed that Jumpcut will copy passwords into the buffer just like all other data.  While this isn't a big issue, it has the potential to be a problem if someone is snooping on your Mac.

Jumpcut should ignore any sensitive data you copy from apps such as 1Password, KeePassX/XC or Keychain Access. 

This should be doable for all applications that mark their data as "transient".  

In the case that this hasn't be implemented for an application, there should be a blacklist preference/functionality so you can make sure that any apps you add to the blacklist won’t add your copied sensitive data to Jumpcut.  This might be more problematic to accomplish.

Thanks again.

**Comment by Gatada** [comment]
I believe this is already implemented:
"Suppress recording pasteboard updates when marked with PasswordPboardType."

**Comment by bunk3m** [comment]
Thanks @Gatada .  

At the moment, Jumpcut 0.63 still copies the passwords from KeePassX and KeePassXC.  

I presume this can be happening if KeePassX and KeePassXC don't identify the PasswordPBoardType or Jumpcut 0.63 doesn't suppress the identified copy.

How do I check where the issue is?

**Comment by snark** [comment]
@Gatada @bunk3m FWIW I've got notes on providing a mechanism for excluding applications from the Jumpcut history, but it's going to wait until after the 64-bit-clean build is released, since that's a hard deadline after which Jumpcut will stop working.

**Comment by snark** [comment]
@Gatada @bunk3m The 64-bit version of Jumpcut provides an option to ignore clippings from applications that support the NSPasteboard.org standard for "concealed" content, including KeePassX/KeePassXC. (I've also added in 1Password, per the suggestion at NSPasteboard.org.) Hopefully the release will be out in the next week or two!

**Comment by Gatada** [comment]
That's great!

I have had to move to Flycut, which is a free AppStore distributed variant. But it has some bugs, so looking forward to moving back to the grandaddy.

**Comment by bunk3m** [comment]
Thank you Steve!  I look forward to trying the new beta.  This is great news!!!  Thank you!

**Comment by acca** [comment]
I'm using Jumpcut v0.72 and I'm saving password with the marker `org.nspasteboard.ConcealedType` (from NSPasteboard.org) using this `pbcopy` alternative: https://github.com/alyssais/secure-pbcopy.

Unfortunately Jumpcut still record it. @snark Do you have any suggestions? I'm available to do further testing

**Comment by snark** [comment]
@acca Sorry for the long radio silence on this! If you're still experiencing this behavior in 0.74 with the "Ignore confidential clippings" preference active, let me know; I just built a copy of secure-pbcopy and can confirm that for me (running Big Sur, 0.74) the behavior is as expected: when the preference is enabled, secure-pbcopy doesn't hit Jumpcut's store, and when it is not enabled it does.

**Comment by snark** [comment]
@acca That said, I think this may be related to issue #55; I'm not sure why the check of one set of types was giving me issues when the other wasn't, since the code was identical, but I'm going to switch both to a check methodology that seems to work better for transient types. The change will go out as 0.75.

**Comment by snark** [comment]
@acca Confirmed against secure-pbcopy in version 0.75, which is now available on GitHub. It should show up in Homebrew and Sparkle autoupdate shortly. Thanks so much for the bug report!
