### ISSUE TITLE
Feature Request - ability to cancel a paste

### ISSUE THREAD

**Issue by petered** [snark/jumpcut#105]
Maybe this exists already - but I didn't find the option - in which case the actual feature request is to make this clear. 

I'll often use Option-Command-V to just quickly lookup something I'd copied before - without wanting to paste it.  But once I'm in there - I have no choice but to paste it somewhere.  Option-Command-Escape would be the natural thing to do, but this is already wired to "force quit applications" on Mac.  

Maybe Command-Option-X to cancel paste?

---

BTW I love this tool you made - big fan.  I probably use it over a hundred times a day.

**Comment by snark** [comment]
@petered While the bezel is displayed, hitting escape instead of releasing the hotkey will cancel the paste, just like you would use the arrows (or repeatedly use of the trigger hotkey with or without shift) to go back through your history. Glad you like it! As I build out features, I should figure out a mechanism to make it more obvious what's supported (e.g. when the bezel's up, you can use the digits 1-9 and Home/End).

**Comment by petered** [comment]
Thanks @snark for checking it out.  I think the problem is that Command-Option-Escape is already wired to "force quit" on mac.  See screen recording: 

https://github.com/snark/jumpcut/assets/1148799/861ad425-75f7-458d-a08b-1b4d66ba471a

**Comment by snark** [comment]
@petered Oh, I get it! *Clearly* I have to document this better. If you're using command-option-V as your trigger, as long as you're holding down any modifier key, the bezel does not dismiss. So if you hit command-option-V, you can release command and still use the arrow keys etc. to navigate, or hit escape.

**Comment by petered** [comment]
Ahhhhh got it! 

```
Command ^_________
Option  ^^_____^^^
V       ^^^_^^^^^^
Escape  ^^^^^^^^^_
```

Ok - in that case my feature request would be still to enable Command-Option-X (or I guess just hitting X while the bezel is open) to close the bezel, because it's a little more intuitive, not bound as an existing MacOS hotkey, and non-pianists can do it with one hand.

Anyway, whatever you go for - appreciate you making this tool.

**Comment by snark** [comment]
Some sort of user-defined hotkey behavior beyond the main hotkey is something that I've considered for a long time, but I've never figured out what the interface should be. I'll keep it in mind, though -- and thanks again for the feedback, which I genuinely appreciate.
