### ISSUE TITLE
The "Master Hotkey" text field shows up white in Dark Mode

### ISSUE THREAD

**Issue by mkania** [snark/jumpcut#15]
![Screen Shot 2019-08-23 at 11 47 36 AM](https://user-images.githubusercontent.com/85564/63605625-58fc2380-c59c-11e9-977a-854f65269ca0.png)

Using Dark Mode on MacOS Mojave, the text shows up white in the Master Hotkey field. I can see it's there when I click on the box, it's just white on a white background.

**Comment by snark** [comment]
Jumpcut is currently using a very old fork of ShortcutRecorder2 (for Xcode target compatibility reasons). I bet this has been patched upstream; I'll see if I can cherry-pick the relevant change.

**Comment by snark** [comment]
Now fixed in master -- credit is due to the ShortcutRecorder2 folks, who have this working in their upstream branch from which I pillaged assets.
