### ISSUE TITLE
Feature request/PR: option to have no icon in the menu bar

### ISSUE THREAD

**Issue by luxmentis** [snark/jumpcut#20]
Long time Jumpcut user here. Nice to see the update.

I like to keep the number of icons in my menu bar to a minimum, and for many years have been using a hacked version of Jumpcut with no menu bar icon. Prompted by the new update, I've forked the repo and implemented the feature in a more user-friendly way:

- added fourth option "No menubar icon" under Preferences - Appearance - Menu display
- added explanatory text (see next item)
- when there's no menubar icon, opening the app when already running brings up the preferences window

I'll submit a pull request - let me know what you think.

**Comment by snark** [comment]
I think if there's no menu item, we should probably fall back to including Jumpcut in the Dock -- that's the standard behavior I've seen on other menubar-only applications that provide that kind of option. Let me think about this. Doing this would I think definitely bar Jumpcut from ever going into the Mac App Store, although that's an unlikely thing to happen at this point. (Neat fork, though -- I strongly encourage that kind of experimentation!) 

I presume based on revealed preference that you'd prefer your ultra-clean behavior to a Dock icon?

**Comment by seldomseenkid** [comment]
Yes, you're right about my preference for no dock icon - in fact I'd be unlikely to use the app at all if it had a dock icon (and I couldn't fork & modify).

The reopen-to-show-window behaviour I'd seen before - just did some hunting through my tools and found that BetterSnapTool uses the same solution to lack of UI, and it's even in the Mac App Store.

I don't have any great attachment to this feature getting into the mainstream codebase - I'm happy that I can modify the app to my taste. But I'd think there'd be others like me - the audience is likely to be customisers/power users and would often have multiple such tools (like me), which puts menu bar space at a premium. Add to that Mac users' general tendency to be clutter-averse, and there you go.

Anyhow, thanks for your efforts modernising the code and making it Catalina-compatible.

**Comment by snark** [comment]
Interesting -- I'll check BetterSnapTool out. (I'm a Magnet user.)

One possibility would be making this a hidden UI preference, although I'd still like to figure out some way of indicating that it's running rather (single dismissible window on launch, maybe?) rather than let Jumpcut run as a poor man's keylogger.

**Comment by hooskers** [comment]
Just want to give my two cents: I have BetterTouchTool and Alfred running this way (no dock *or* menu icons) and I love it. I would love to have this in Jumpcut, as well!

**Comment by seldomseenkid** [comment]
@snark This doesn't address your concern directly, but another option would be to provide a popup menu in the bezel that gives access to the preferences and other UI. Quicksilver (like Alfred) and DTerm (terminal anywhere) do this.

This discussion makes me realise just how long I've been using some of these tools. Muscle memory is valuable.

**Comment by snark** [comment]
@seldomseenkid @hooskers I've thought about it off and on over the last few months, and I think I'm going to go with that approach (a popup menu in the bezel). As such, I think this is blocked by some revamps I'd like to make to the bezel behavior, so it won't happen immediately (you may have noticed that releases are slow), but I think that suggestion is an approach I can go forward with.

When I hit that point, I'll check out your PR!

**Comment by snark** [comment]
@luxmentis @wadjoh There's a fairly significant rewrite coming, and I've--years later!--got this on the roadmap.

**Comment by snark** [comment]
@luxmentis @wadjoh This will be forthcoming in the next release, hopefully in the next month or so. Thank you for your patience!

**Comment by snark** [comment]
@luxmentis @wadjoh Boom, it took *forever* to get this release done—Jumpcut is now written in Swift, so I couldn't use @luxmentis' PR (but I truly appreciate the effort), but this is now a feature under the "Appearance" tab in Jumpcut's preferences.
