### ISSUE TITLE
No process name

### ISSUE THREAD

**Issue by danielcompton** [snark/jumpcut#22]
In the [v0.70](https://github.com/snark/jumpcut/releases/tag/v0.70) release of Jumpcut, I'm not seeing a process name in Activity Monitor, nor in the Privacy tab in System Preferences > Security. I just checked, and the process name is present in [v0.7.0-beta1](https://github.com/snark/jumpcut/releases/tag/v0.7.0-beta1).

<img width="286" alt="Screenshot of Activity Monitor (12-09-19, 10-28-32 AM)" src="https://user-images.githubusercontent.com/811954/64798191-367c7b00-d548-11e9-85d0-674fdcb7f7a3.png">

<img width="346" alt="Screenshot of System Preferences (12-09-19, 10-28-19 AM)" src="https://user-images.githubusercontent.com/811954/64798195-38463e80-d548-11e9-8004-bd92a108af30.png">

Looking at the [diff](https://github.com/snark/jumpcut/compare/v0.7.0-beta1..v0.70), it seems like possibly some of the keys in the [Info.plist](https://github.com/snark/jumpcut/compare/v0.7.0-beta1..v0.70#diff-18029c7f27aa04496a2b943076c36126) need to be set?

This is on macOS Mojave 10.14.6.

**Comment by snark** [comment]
Super weird; thanks for the catch.

**Comment by snark** [comment]
Okay - the fix is in master. I'm hoping to release 0.71 with some small bug fixes next week; this will go into that. Thanks again for the report!
