### ISSUE TITLE
Damaged and can’t be opened.

### ISSUE THREAD

**Issue by DenVog** [snark/jumpcut#24]
When I launch v0.71 I get an error "“Jumpcut” is damaged and can’t be opened." I have tried downloading the tar file Jumpcut-0.71.tar.bz2 with both Safari and Chrome. The app unpacks fine, but when I launch I always get the error.
https://github.com/snark/jumpcut/releases/download/v0.71/Jumpcut-0.71.tar.bz2

**Comment by jamesbisset** [comment]
Same here. Here’s a screenshot:
![Screenshot 2019-09-19 at 17 33 04](https://user-images.githubusercontent.com/211461/65263138-cd76a380-db03-11e9-927e-12ce1890a49b.png)

**Comment by salbjerg** [comment]
Same here.

**Comment by snark** [comment]
Thanks; I'll yank the asset and try reloading.

**Comment by snark** [comment]
Yeah, it looks like something weird happened when my script generated the archive. I'll pull it down.

**Comment by snark** [comment]
@jamesbisset @salbjerg @DenVog My script used the wrong `tar` commands to create a bz2 file. Absolutely classic: https://www.xkcd.com/1168/ 

Anyway, I fixed the issue and replaced the file with one confirmed to work on a machine running High Sierra. Please let me know in this issue if you can confirm!

**Comment by salbjerg** [comment]
Your new version of Jumpcut 0.71 works fine, thank you.
(MacOS 10.14.6)

**Comment by snark** [comment]
Thanks! Sorry for the inconvenience.
