### ISSUE TITLE
New installs don't get default master hotkey

### ISSUE THREAD

**Issue by snark** [snark/jumpcut#27]
Pulled from issue #12:

```10.15 Beta (19A558d)
Appears to work on Catalina Beta without issue.  No default master hotkey
is configured on a fresh system, which could confuse new users.
```

I'm not sure if this is an issue with Catalina or how the default settings are configured for ShortcutRecorder.

**Comment by lookfirst** [comment]
I just came from Flycut and I'm on Mojave and I ran into this. I'm also used to shift-command-v, but 🤷‍♂ ...

Also, the text is tiny... could be made a bit larger...

![image](https://user-images.githubusercontent.com/85355/66555109-51a6ce80-eb78-11e9-9882-4ee95ff902d0.png)

**Comment by snark** [comment]
Fixed in 0.72. Thanks for the bug reports, folks!

**Comment by lookfirst** [comment]
https://github.com/Homebrew/homebrew-cask/pull/77467

**Comment by snark** [comment]
Thanks, @lookfirst -- I was going to issue that PR today to allow a little time to ensure that there were no problems with the build. (You haven't experienced any?)

**Comment by lookfirst** [comment]
@snark All good for me!
