### ISSUE TITLE
0.71 Crashes on pasting with hotkey (Sierra/10.12.6)

### ISSUE THREAD

**Issue by gabrielboucher** [snark/jumpcut#29]
How to reproduce on macOS Sierra 10.12.6:

Deleted 0.63 to Trash
Installed 0.71 from brew cask
Went to System Preferences to remove and re-add to Privacy settings
Manually assigned a hotkey cmd-alt-v (Since it's not getting assigned by default)
Copy and paste using the hotkey
Result: the jumpcut box is shown, the string is pasted, jumpcut crashes

**Comment by snark** [comment]
Thanks for the bug report, @gabrielboucher -- I'll have to find a computer running Sierra to replicate; the oldest OS I have easy access to is running 10.13.

**Comment by tombot18** [comment]
I'm having exactly the same problem on 10.12.6. Let me know if there's anything I can do to help debug.

**Comment by snark** [comment]
@gabrielboucher @tombot18 I'm going to try to resolve this in 0.72.

**Comment by snark** [comment]
@tombot18 @gabrielboucher Okay, a friend is trying to replicate and I have access to an older MBA that I am going to try to wipe and put Sierra on; it's currently running 10.13. Is there anything I should try to reproduce about your setup? It's using the US keyboard? (Were there any stack traces or anything when Jumpcut crashed? Was anything useful in Console.app?)

**Comment by tombot18** [comment]
@snark - I'm on a mid-2010 Mac Pro using a UK Keyboard. 

**2 methods to recreate issue:** 

First method:
1. Open Jumpcut preferences from status bar icon.
2. Select 'hotkeys' pane
3. App will crash and require manual restart.

Second method:
1. Attempt to paste using the configured hotkey
2. App will crash and require manual restart.

See attached crash logs:
[Jumpcut-Crashes.zip](https://github.com/snark/jumpcut/files/4031165/Jumpcut-Crashes.zip)

**Comment by snark** [comment]
@tombot18 Thanks much.

**Comment by snark** [comment]
Okay, on a machine running El Capitan, I've replicated this behavior. It seems to be an issue with how the hotkey is writing itself into the application preferences, quite possibly related to the age of the fork of ShortcutRecorder 2 I'm using. If I can't solve it with a simple hack to the serialization, I'm going to have to upgrade to mainline SR2, which should bring some additional bug fixes at the cost of more refactoring to Jumpcut's code.

**Comment by snark** [comment]
I've confirmed that the code currently in master fixes the issue on El Capitan; I presume it will do so on Sierra as well. Release forthcoming in the next couple of days.

**Comment by snark** [comment]
@gabrielboucher @tombot18 0.72 is released; I'll push out a Sparkle appcast change and update the brew cask shortly. Want to try downloading it from the releases page and see if it fixes your issues? I validated the fix personally on an old MacBook Air running El Capitan but don't have a machine running Sierra to test against; it should work, however.

**Comment by tombot18** [comment]
@snark - perfect that fixed it for me. Nice one!

**Comment by snark** [comment]
Confirmed fixed! Thanks again for the bug report.
