### ISSUE TITLE
Jumpcut reports itself as 32-bit on Mojave

### ISSUE THREAD

**Issue by snark** [snark/jumpcut#34]
Checking the System Profile legacy apps list, Jumpcut seems to report itself there even though it is 64-bit. Mysterious! Possibly not fixable, if it's related to the use of something like Sparkle.

**Comment by snark** [comment]
See issue #32 where this was initially reported.

**Comment by salbjerg** [comment]
Reading https://kirkville.com/legacy-software-in-macos-catalina/
on a Mac Mojave where 64-bit Jumpcut 0.71 shows up as 64-bit in
Activity Monitor but as 32-bit in System Information / Legacy Software
leads to speculation that output from System Information.app (in both
Mojave and Catalina) might be suspect.

**Comment by snark** [comment]
Closing this; we're on 0.74, which is correctly reported as a Universal binary.
