### ISSUE TITLE
Clipping selection pastes active even when not selected

### ISSUE THREAD

**Issue by rajatsrivastava95** [snark/jumpcut#35]
Version 0.71

"Clipping selection pastes" in not selected but a "paste" is still issued to the app.
![image](https://user-images.githubusercontent.com/9687921/71699080-96ab5d00-2d83-11ea-8ade-4a6e45318fb8.png)

**Comment by snark** [comment]
Thanks for the report, @rajatsrivastava95; 0.72 restores the separate checkboxes for menu- and bezel-based clipping preferences, as seen in versions of 0.6x.

**Comment by rajatsrivastava95** [comment]
Cool works great now. Thanks!
