### ISSUE TITLE
0.71 crashes on input method change

### ISSUE THREAD

**Issue by nodje** [snark/jumpcut#38]
Same as others, I've been using your utility for years with so much satisfaction.
Small and light, it's incredibly useful and productive, better than all others I've tried so far.

Just simple enough and out of the way I guess.

And I recently took the Jump to Catalina and it didn't make the cut :)

I'm a heavy Chinese- Pinyin input method user, and I can conveniently use Caps-Lock to switch one keyboard to the other.
Caps-Lock just makes 0.71 crash immediately.

I imagine this is going to be hard to reproduce and fix if you're not an alternative input method user yourself.

The easiest way to reproduce i'd say, would be to install Macos included Chinese 
"Pinyin-simplified", make sure the "Use Cpas Lock key..." is checked and then it should crash!

Adding a pic for convenience below.

![Screenshot 2020-02-03 at 10 11 10](https://user-images.githubusercontent.com/75604/73639970-b4632f00-466d-11ea-9129-1b226d319ac0.png)

**Comment by snark** [comment]
@nodje I believe this is the same as issue #30, which was reported for Hiragana keyboards. I have a fix written and in master that has been confirmed to work for that, but I've been delaying a release in the hopes of resolving a few other bugs as well. It sounds like this makes Jumpcut genuinely unusable for people using Asian-language inputs, so I'll commit to doing a release by the end of next week regardless of whether I have anything else fixed.

**Comment by nodje** [comment]
Thank you for dropping a note!
Were I more at ease with Macos apps compiling and packaging, I'd def. give a try to your commit I just had a look at. But unfortunately I'm not :)
So will wait for your release and let you know!

**Comment by snark** [comment]
I just confirmed that on the 0.72 beta I can switch inputs between English and Pinyin with no crashing, so I'm pretty sure it's the same bug. I'm still shooting for a release next week, probably February 19 or 20.

**Comment by snark** [comment]
@nodje 0.72 is released; I'll push out a Sparkle appcast change and update the brew cask shortly. Want to try downloading it from the releases page and see if it fixes your issues?

**Comment by nodje** [comment]
Working so far!
Closing the issue
