### ISSUE TITLE
Catalina update?

### ISSUE THREAD

**Issue by digiology** [snark/jumpcut#40]
I'm saddened to see that Jumpcut doesn't work after updating my OS. Will you be updating Jumpcut for Catalina?

**Comment by snark** [comment]
@digiology It's been done. 😃 Check out installation instructions here: https://snark.github.io/jumpcut/

(Updating via Sparkle from 0.63 is a known problem, but you can download a fresh binary or install via Home-brew.)

**Comment by snark** [comment]
@digiology That said, please leave a note here if you're having trouble installing (or send me an email), and I'll reactivate the issue.

**Comment by digiology** [comment]
Thank you for responding. It looks like something went wrong during installation and I was opening the old version. 

Much love, 
Jumpcut Fan
