### ISSUE TITLE
Mac OS Catalina Compatability

### ISSUE THREAD

**Issue by thallstein** [snark/jumpcut#43]
Upgraded to Catalina and receive message Jumpcut needs to be updated when I try to launch Jumpcut. Was warned by OS pre-update it might break.

**Comment by snark** [comment]
@thallstein Try downloading a fresh copy here: https://snark.github.io/jumpcut/

For a variety of reasons related to the age of Jumpcut 0.63, upgrading directly from the application doesn't work. Please note that you'll probably need to follow the instructions given as "Note to Upgraders" on that page.
