### ISSUE TITLE
Jump cut image is not dignified in black background

### ISSUE THREAD

**Issue by mataney** [snark/jumpcut#46]
Hi all, a pretty random issue, but the image of jumpcut when the background is black (Like in 
terminals) is really not dignified. I received a few strange faces in the office already 😨 

Can we change this so maybe the scissors image will always be displayed and not just the outlines?

let me know if I really need to add a photo..

**Comment by snark** [comment]
@mataney You weren't the only one with that reaction. As of the 0.7* releases, the outlined Jumpcut image is no longer displayed!

**Comment by snark** [comment]
@mataney (Feel free to reopen this issue if I missed a spot to remove it somewhere, but I just checked 0.72 and it's not visible to me.)
