### ISSUE TITLE
When pasting a copied selection, the pasted selection appears as a new copy in Jumpcut

### ISSUE THREAD

**Issue by Web-Betty** [snark/jumpcut#48]
Whenever I paste multiple selections at a time using Jumpcut, the _pasted_ selections are then added as the most recent selections I've copied. Here is a [link to a video](https://www.screencast.com/t/leRa0MlM) showing what is happening.

**Comment by snark** [comment]
Thanks for the screencast! That's a definite regression, which I've reproduced. I personally drive Jumpcut using the keyboard, where that isn't occurring. I'll investigate and try to get a fix out soon.

**Comment by Web-Betty** [comment]
Hello,

A screencast is worth a thousand words, lol!

The problem occurs regardless of how the copy and paste is done, mouse click or keyboard shortcuts. My use case is that I will need to copy multiple items to the clipboard at once, and then paste them, in the copied order. This [new video](https://www.screencast.com/t/Og6og1mfkI) shows what happens—when I copy three items using the keyboard, and then paste them in copy order, the pasted selections show up as new clips. (I used keyboard shortcuts command + c and command + v)

If I copy one item and paste it, it's not re-added as a new clip. But as soon as you paste multiple items from the list, they are re-added. Here's the [screencast showing this behavior](https://www.screencast.com/t/A58Or5ta74F).

**Comment by snark** [comment]
@Web-Betty Okay, I tracked this down and fixed it; it'll be in the next release, which I hope to get out the door sometime in the next month or so. Would you like a thank-you in the release notes? If so, would you like to be thanked as "GitHub user Web-Betty", or a different name?

**Comment by Web-Betty** [comment]
Yay! Looking forward to a fix. You can use Web-Betty. :)
------------------------------
[image: Urban Nymph Photo]


Melissa Johnson
*digital heart, analog soul*

 www.urbanymphoto.com

 melissa@web-betty.com |  303-895-0017


------------------------------

**Comment by snark** [comment]
0.73 has been released. Thanks again for the reproduction info!
