### ISSUE TITLE
log message: Could not find and/or execute program specified by service

### ISSUE THREAD

**Issue by LB62** [snark/jumpcut#50]
Hello.
I'm currently not using Jumpcut, but I see in the Apple Message Log a lot of msg like this:

22 ago 2020, 18:54:31 com.apple.xpc.launchd[1]: Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: net.sf.jumpcut.JumpcutHelper
22 ago 2020, 18:54:31 com.apple.xpc.launchd[1]: Service exited with abnormal code: 78
22 ago 2020, 18:54:31 com.apple.xpc.launchd[1]: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

Is it normal? How can remove these msgs?
It's not a problem for the messages, but that the Apple Message Log is full of these and so error msgs from other apps are deleted and can't read them.
Thanks

**Comment by snark** [comment]
@LB62 That curious! "JumpcutHelper" is the app used for launch-on-login, but it's signed so it shouldn't be quarantined. I'll investigate. What version of Jumpcut do you have installed? There was very briefly a release with a bad signature, but the odds that you downloaded a copy during the 20 minutes it was posted seem slim.

At a minimum, if you're not using the application, we should be able to remove the call from Launch Services, but I'm puzzled about what's going on.

**Comment by LB62** [comment]
I've installed the last version of Jumpcut, but surely there was an older version I did install before, don't remember which one.
Still my log is full of the same messages, they repeat every 10 seconds.
But the question is that I can't find any JumpcutHelper file on disk, even searching within the system files and the invisible files in Finder, so how can remove whose annoying messages in the log?
