### ISSUE TITLE
Feature request: Make confirmation for the Clear All command optional

### ISSUE THREAD

**Issue by monkeyhybrid** [snark/jumpcut#52]
It would be nice to have an option to make confirmation for the _Clear All_ command optional. Currently, you click on _Clear All_ and then have to confirm this action by clicking _Clear_ in the popup confirmation window. Personally, I've never needed to cancel this operation and it's bit of an annoyance for my workflow.

**Comment by snark** [comment]
@monkeyhybrid Bam, new feature in the confirmation window in 0.75. Enjoy!

**Comment by monkeyhybrid** [comment]
Thanks for this, you're a star!

**Comment by monkeyhybrid** [comment]
Just wanted to follow up with a quick thank you now that I've updated to 0.75 and tested this. It works great! Cheers!
