### ISSUE TITLE
Feature Request: Ignore Passwords from Password Manager - spec. Enpass

### ISSUE THREAD

**Issue by maybeageek** [snark/jumpcut#55]
Hi,

thanks for this amazing small OpenSource tool. Really useful! However, I'd love for it to ignore copy&pastes from my password manager, Enpass.

Best from Germany

**Comment by snark** [comment]
Jumpcut supports the semi-standard list of ignorable pasteboard types at http://nspasteboard.org, which I believe means that MacPass, 1Password, and LastPass will all be ignored. Is Enpass open source? Failing that, can you use something like this code snippet to tell me what the pasteboard type set by Enpass is? https://gist.github.com/JohnCoates/47218d0f82f97219685c

**Comment by maybeageek** [comment]
Hi,

this is the output I got using that code snipet. If this does not suffice, Enpass has good responding developers, that implemented several of my feature requests in the past. I am sure they will listen if there is a good benefit.

`2021-01-13 09:17:02.598 writeOutPasteboard[14767:232780] items: (
    "<NSPasteboardItem: 0x7fca27006040>"
)
2021-01-13 09:17:02.603 writeOutPasteboard[14767:232780] types: (
    "org.nspasteboard.TransientType",
    "public.utf8-plain-text"
)
2021-01-13 09:17:02.604 writeOutPasteboard[14767:232780] org.nspasteboard.TransientType: (null)
2021-01-13 09:17:02.604 writeOutPasteboard[14767:232780] org.nspasteboard.TransientType: (null)
2021-01-13 09:17:02.605 writeOutPasteboard[14767:232780] public.utf8-plain-text: myCopiedPassword
2021-01-13 09:17:02.605 writeOutPasteboard[14767:232780] public.utf8-plain-text: {length = 14, bytes = 0x79387266794c2132794b6a57735a}`

**Comment by snark** [comment]
Thanks!

**Comment by snark** [comment]
@maybeageek Okay, I've reproduced; I'm not entirely sure why the behavior isn't doing what I expected. Even though code was identical for the checks for the "transient type" used by Enpass and the "concealed type" used by e.g. KeePassX, the Enpass check wasn't working properly. (That said, there may have be something strange going on with concealed types as well, per issue #10.

I've updated the behavior of the check and it now seems functional; it'll go out in 0.75 in the not-too-distant future.

Thanks for the bug report and for your patience!

**Comment by snark** [comment]
@maybeageek And 0.75 is now available on GitHub; it should be available from Homebrew and Sparkle autoupdates soon.  Please let me know if the problem continues, but I did verify the fix against a copy of Enpass. Thanks so much for the bug report!

**Comment by maybeageek** [comment]
Just a comment: Yes: it is fixed for me (Enpass user) in this version!

Thanks a lot!

**Comment by kapi-caz** [comment]
Hi @snark, I'm using MacPass and unfortunately it doesn't ignore those passwords. I've enabled the flag in the preferences 'Ignore confidential clippings'. 
I use:
jumpcut 0.75
Big Sur 11.5.2
MacPass 0.7.12

**Comment by snark** [comment]
@kapi-caz I'm happy to take a look and see if I can figure out what pasteboard type MacPass is using.

**Comment by snark** [comment]
@kapi-caz It looks like this is a MacPass issue that's addressed in this commit from June 2020: https://github.com/MacPass/MacPass/commit/c759aeddd9ecf790a37c40425a1210d2f395c016

However, 0.7.12 was released in March 2020, so I'm pretty sure getting the correct behavior will require either a fresh MacPass release or switching to the nightly build. (I believe the MacPass maintainer has been working on a Big Sur-friendly release, so hopefully that will come soon!)

I have a significant rewrite of Jumpcut in progress—no promises about when I'll deliver it, as I've only been working on it in a scattershot way—in Swift, and one thing I'd like to add is the ability to add applications to an ad hoc "ignore" list.
