### ISSUE TITLE
Native version for M1 Macs

### ISSUE THREAD

**Issue by msagarpatel** [snark/jumpcut#59]
Thanks for creating Jumpcut! Are there any plans for a native, release version for M1 Macs?

**Comment by snark** [comment]
I spent a couple hours updating some dependencies and I have a working Universal build, which I'll release sometime this week. Thanks for prodding me!

**Comment by snark** [comment]
And we're up! I'll update the Sparkle appcast soon, but version 0.74 is now uploaded to GitHub after some light testing on an M1 Air and an Intel MacBook Pro.

**Comment by msagarpatel** [comment]
Awesome, it works! Thanks, @snark!
