### ISSUE TITLE
Let users hide jumpcut from menu bar

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [snark/jumpcut#61]
Like any other app, it would be great to be able to hide jumpcut from the menu bar:

![image](https://user-images.githubusercontent.com/5295554/129088362-9b8e85e7-26bb-4d87-ba2d-b4688d60dcd3.png)

**Comment by snark** [comment]
Duplicate of #20 -- I've been thinking about this, however! It will probably come in the 0.8 branch/Swift rewrite.
