### ISSUE TITLE
Excessive top margin/padding in bezel. v0.75

### ISSUE THREAD

**Issue by YBPN** [snark/jumpcut#62]
Thank you for this app. Been using it for a long time. 

This is on El Capitan, OSX 10.11. This is what the bezel looks like. The top half of the bezel is empty space. 

![Screen Shot 2021-09-03 at 9 50 42 PM](https://user-images.githubusercontent.com/68190891/132016655-b35d6140-339b-4a20-9171-4ad0a3bceccf.jpg)

**Comment by snark** [comment]
Ha -- this is the remnants of an old image (a big dotted outline of the scissors) that used to appear there. You're right that it looks pretty dumb as it is.

**Comment by larslehners** [comment]
+1

**Comment by x029a** [comment]
+1, this is still present.

**Comment by snark** [comment]
@YBPN @larslehners @x029a I've slimmed this down a lot in the new 0.80 (although it's still got a big top margin, due to personal preference/historical continuity). The next release will probably add some additional controls around the bezel appearance.

**Comment by snark** [comment]
Closing this one out, as I'm satisfied with the (still top-heavy) current appearance of 0.80 forward. I will be adding some additional appearance options at some point!
