### ISSUE TITLE
"Clear All" when list is empty crashes program

### ISSUE THREAD

**Issue by CHigginbotham** [snark/jumpcut#65]
It's probably an edge-case bug. because why would anyone clear Jumpcut when it's already empty. 
Nonetheless the application crashes when trying to clear an already cleared Jumpcut list of clippings. 
The list is non-existent and so cannot be cleared.

Affects version: 0.80

Steps to reproduce:
1. Open Jumpcut
2. Copy something to clipboard
3. Click the menu bar icon
4. Clear all clippings
5. Clear again and the app crashes

**Comment by monkeyhybrid** [comment]
Was just about to raise an issue for this too, after updating to 0.8. Muscle memory makes me 'Clear All' quite often throughout the day, whether the clipboard is empty or not.

**Comment by snark** [comment]
I anticipate a new version full of fixes for these regressions being released later this week.

**Comment by snark** [comment]
@CHigginbotham @monkeyhybrid This is why we should write test. My dumb error has been corrected in 0.81. Thanks for the bug report!
