### ISSUE TITLE
Version 0.80 doesn't allow ctrl+shift+@ to reverse order select items

### ISSUE THREAD

**Issue by Vadorequest** [snark/jumpcut#66]
I upgraded today and since then I cannot use the `ctrl+shift+@` shortcut to go backwards in history.

My custom shortcut is `ctrl+@`. This has worked fine for years.

**Comment by snark** [comment]
@Vadorequest To be clear, that's Control-Shift-2 for the hotkey? Or are you using a keyboard layout where "@" has a dedicated key?

If the former, what's your expectation for reversing? If the latter, what's the keyboard layout in question?

**Comment by Vadorequest** [comment]
@snark Hi! Here is a short recording to lift all confusion :) 

https://watch.screencastify.com/v/7cIvctJqtc3CqgKQaE8s

And here is what my keyboard looks like
![image](https://user-images.githubusercontent.com/3807458/165993221-70670e40-2348-4de6-ae72-8d3cb8954882.png)

**Comment by snark** [comment]
@Vadorequest Thanks; I'd love to replicate this so I can see what's going on, but that doesn't seem to be a standard French/AZERTY keyboard. Do you happen to know what keyboard type macOS thinks that is? When I switch to AZERTY on my (QWERTY, US) laptop, I get the angle brackets in that space. (&/1 and é/2 match the positions in the photo.)

**Comment by Vadorequest** [comment]
It's a traditional macOS French keyboard. 

Here is a detailed video of the keyboard layout.
https://watch.screencastify.com/v/HGcbHNhxde0i3nsCKDsg

The problem happens with my 2 MacOS computers (I just got a new one), both have the same keyboard layout.

**Comment by Vadorequest** [comment]
I uninstalled 0.80 and went back to 0.75, works like a charm.

**Comment by snark** [comment]
@Vadorequest Can you contact me at the email address listed in my GH profile? I think I've tracked down the (somewhat subtle) logic bug that is causing this problem, but I'd love to send you a prerelease build to make sure it's working in actual use.

**Comment by snark** [comment]
@Vadorequest , the fix you tested is now in 0.81. Thanks!
