### ISSUE TITLE
Menu bar icon options gone in v0.80

### ISSUE THREAD

**Issue by marcinmj** [snark/jumpcut#68]
Petty I know, but I prefer the chunkier white scissors for the menu bar icon. Can we have the horizontal "White scissors" option from v0.75 back in the future update, please. The thin, vertical scissors icon is just not visible enough. Thanks for your hard work.

<img width="628" alt="CleanShot 2022-04-29 at 15 41 16" src="https://user-images.githubusercontent.com/4969600/166077441-b2c57286-6cec-4a28-807c-9ca81c8e2e05.png">
.

**Comment by snark** [comment]
Not petty at all; if I knew anyone preferred the Unicode, I'd have kept it around! I'll add this back in for the next bugfix release.

**Comment by snark** [comment]
@marcinmj The "white scissors" option is back under Appearance in the preference window in 0.81. (The more realistic "black scissors", aka "solid scissors", isn't sized well for the menu bar.) Enjoy!
