### ISSUE TITLE
Using backspace to delete a clip jumps to last clip

### ISSUE THREAD

**Issue by theshillito** [snark/jumpcut#70]
**Jumpcut version:** 0.80 (20220424)
**macOS version:** 12.3.1
**Architecture:** Apple Silicon (M1 Pro)
**Steps to reproduce:**
1. Open Jumpcut
2. Copy to clipboard some text enough times to have multiple clips in Jumpcut
3. Press the hotkey to open the bezel (in my case: option, command and V)
4. Choose a clip to delete and press backspace
5. Notice that the bezel is now displaying the oldest clip rather than the next in-line.

**Additional notes:** Many of the clips in my Jumpcut when seeing this was from the previous non-Swift 5 version of Jumpcut, so I did a "Clear All" and restarted the app just in case, and that didn't make a difference.

**Comment by snark** [comment]
Dumb mistake in the rewrite (wrong variable being used in that behavior); I'll have a fix out in the next release. Thanks for the bug report!

**Comment by snark** [comment]
@theshillito I forgot to mention it I the release notes, but this is fixed in 0.81. Thanks for the bug report!
