### ISSUE TITLE
Whitespace clippings

### ISSUE THREAD

**Issue by barrypress** [snark/jumpcut#71]
It appears that copying strings consisting entirely of whitespace (e.g. 'cr' or "'cr''sp'"; I didn't try "'cr''nbsp'") are ignored by Jumpcut, regardless of their being processed by the pasteboard itself. I suppose this might have been intentional, but it does preclude some useful use cases.

**Comment by snark** [comment]
@barrypress It was intentional - what's the use case? Something like Python formatting? Seemed like an edge case, since there's no good way to distinguish whitespace-only clippings within the bezel or the menu.

**Comment by barrypress** [comment]
I do it, for instance, when I am replacing single line ends with with multiple lines in order to get spaces in text files, and the tool that I have to be working in doesn’t provide a sufficient search and replace capability

I could envision the UI being something like a wavy line of some color or black underneath the white space or even underneath the entire clipping, or vertical bars at the start and end of all clippings, or a selectable character at the start and end of all clippings

Barry

**Comment by snark** [comment]
Thanks! That's a reasonable use case for me to think about. What I may do is provide recording whitespace as an optional behavior in the next minor release, and think about improved UX for it in a later release.

**Comment by pfrank888** [comment]
I also miss the whitespace clippings. My use-case is that I work with a lot of boilerplate text, and I would use the whitespace to highlight the boilerplate that needed to by copied into whatever I'm working, distinguishing it from all the other clippings in the dropdown menu.

Pick out the important boilerplate text from this menu without any whitespace...

<img width="347" alt="Screen Shot 2022-05-04 at 2 16 52 PM" src="https://user-images.githubusercontent.com/104941918/166827417-42b6a52e-8d6e-4762-9670-5eeea48f494a.png">

**Comment by barrypress** [comment]
I’d appreciate that. Thanks very much

Barry

**Comment by snark** [comment]
@barrypress This has now been added as an option in 0.83!

**Comment by barrypress** [comment]
Thanks!
