### ISSUE TITLE
Feature request: Lock to last pasted item

### ISSUE THREAD

**Issue by caewok** [snark/jumpcut#72]
Use case: I would like to be able to use the Jumpcut hotkey to paste an item "A", the copy several items, and use the Jumpcut hotkey to paste the same item "A" I just pasted previously without having to find it again in the bezel menu.

Right now, in Jumpcut 0.8, it remembers the last item used with the hotkey, *but* if you copy additional items into the queue, the hotkey item gets shifted by one. 

For example: 
- Queue is C, B, A where C is the first item and A is the third item
- Use hotkey to paste A.
- Add two new items D and E using copy, so Queue is E, D, C, B, A. The hotkey will have shifted from A to C. Instead, the hotkey should remain at A.

**Comment by snark** [comment]
@caewok Thanks -- this is a bug in the recent rewrite of Jumpcut, as your behavior describes what should be occurring. It'll be fixed in the next release.

**Comment by snark** [comment]
@caewok Actually, on checking, I'm wrong -- the *only* behavior in Jumpcut 0.75 was to reset the bezel position to the top of the stack when new items were copied. That said, the behavior you describe was available in the past (although possibly never in a proper release? The code to do it was commented out in 0.75, but I remember using this behavior in the past, possibly only in personal testing), and will be exposed as a preference in the next release of Jumpcut. Thanks!

**Comment by snark** [comment]
@caewok Fixed in 0.81, with a restored option to either move to the top or continue tracking the last-used item. Thanks for the bug report!
