### ISSUE TITLE
Version 0.80 does not launch at login on Mac

### ISSUE THREAD

**Issue by Jean-ita** [snark/jumpcut#75]
Since I upgraded to version 0.80 on Mac (Monterey 12.3.1) jumpcut does not launch at login even if the setting says so

**Comment by snark** [comment]
@Jean-ita Can you try toggling the setting? The mechanism under 0.80 is slightly different from previous versions, but toggling should get it set properly. I can confirm that it's working under Big Sur; I'll confirm under Monterey shortly.

**Comment by Jean-ita** [comment]
It works as you said.
I thought i did toggled it already, but apparenlty not.
So, it's confirmed that toggling it get it set properly also on Monterey.
Thanks! Jumpcut is great btw!
