### ISSUE TITLE
Feature request: Keep pictures

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [snark/jumpcut#79]
Treat pictures in clipboard the same way you do with texts in clipboard. Also, it would be wonderful to let user save the images to the disk.

**Comment by snark** [comment]
This is quite unlikely to happen -- Jumpcut's focus is going to remain text. You might want to check out @mattDavo's open source clipboard manager Yippy, which I know currently handles images (although with a different interface): https://yippy.mattdavo.com
