### ISSUE TITLE
Deprecate sourceforge?

### ISSUE THREAD

**Issue by fadookie** [snark/jumpcut#9]
I just spent a while fixing the SVN sources of jumpcut to build against SDK 10.11. By chance I just stumbled across this github repo when I was trying to see if anyone else had forked the project.

I think it makes sense to move the main line of development to github as it looks like you have already done. It would be great if the old sourceforge pages were updated to reflect this, so future would-be contributors don't waste the same effort that I just did.

In any case I just implemented a "Paste All" feature - patches are at https://sourceforge.net/p/jumpcut/patches/4/ and my fork is at https://github.com/fadookie/jumpcut
If I get a chance I will set up a proper PR against this repo.

**Comment by snark** [comment]
@fadookie Sorry for wasting your time when this happened! Jumpcut was obviously in a deep, deep development freeze. Now that a 64-bit ready version is out (it's out!) I've put up a meta refresh directing users from the SourceForge page to GitHub, and references to SourceForge in the code have been removed.

**Comment by elashpear** [comment]
Thanks! Since I posted this I've switched to the Flycut fork which has this feature and more.
