### ISSUE TITLE
"No Save Access" error after updating to 0.83

### ISSUE THREAD

**Issue by KTamas** [snark/jumpcut#96]
Got a warning Jumpcut has "No Save Access" because it didn't have permissions to `~/Library/Application Support/Jumpcut`. I gave it Full Disk Access in Security, same error. Then I went to check on the folder and turns out it didn't exist at all? Manually created, all good now, but this was a non-issue before the update.

**Comment by jonnyr** [comment]
I had the same issue as well but followed what @KTamas did and it worked perfectly as well. Thanks for the workaround until you have time to update!

**Comment by snark** [comment]
@jonnyr @KTamas I corrected the check/directory creation behavior in 0.84. Thanks for the bug report!
