### ISSUE TITLE
Check for updates doesn't find 0.84

### ISSUE THREAD

**Issue by swrobel** [snark/jumpcut#97]
<img width="260" alt="Screenshot 2023-12-05 at 12 46 16 PM" src="https://github.com/snark/jumpcut/assets/157270/f5275c96-fa02-4dfa-b826-99f82a850722">

**Comment by snark** [comment]
Thank you! It was a cut-and-paste error in the Sparkle appcast, ironically; l hadn't bumped the version listed for 0.84.
