### ISSUE TITLE
Update to 0.84 showing even after updating

### ISSUE THREAD

**Issue by jvlobo** [snark/jumpcut#98]
I got a notification to update to version 0.84, which I did, but then the notification to update to 0.84 keeps showing even though I'm on version 0.84 already (confirmed by checking in the "About Jumpcut" section).

**Comment by snark** [comment]
Ugh -- when I fixed a typo in the Sparkle appcast preventing it from updating, I put the wrong version in there, so 0.84 thought there was a later version than itself. Fixed now, no changes to the software required. Thanks for the bug report!
